extends RefCounted
class_name BetCatalog

const BET_DEBT_CHAIN: StringName = &"DEBT_CHAIN"
const BET_BLOOD_TAX: StringName = &"BLOOD_TAX"
const BET_CROW_PLEASER: StringName = &"CROW_PLEASER"
const BET_LAST_BREATH: StringName = &"LAST_BREATH"

const BET_P3_WAX_SEAL: StringName = &"P3_WAX_SEAL"
const BET_P3_BLOOD_LEDGER: StringName = &"P3_BLOOD_LEDGER"
const BET_P3_DEBT_MIRROR: StringName = &"P3_DEBT_MIRROR"
const BET_P3_CROWD_FEAST: StringName = &"P3_CROWD_FEAST"
const BET_P3_LAST_WAGER: StringName = &"P3_LAST_WAGER"
const BET_P3_RED_VERDICT: StringName = &"P3_RED_VERDICT"
const BET_P3_CHAIN_OATH: StringName = &"P3_CHAIN_OATH"
const BET_P3_TITHE_OF_BONE: StringName = &"P3_TITHE_OF_BONE"
const BET_P3_GLORY_TAX: StringName = &"P3_GLORY_TAX"
const BET_P3_MERCY_BAIT: StringName = &"P3_MERCY_BAIT"
const BET_P3_SILENCE_BRIBE: StringName = &"P3_SILENCE_BRIBE"
const BET_P3_FINAL_APPLAUSE: StringName = &"P3_FINAL_APPLAUSE"
const BET_P3_LIE_MERCY: StringName = &"P3_LIE_MERCY"
const BET_P3_LIE_DEBT: StringName = &"P3_LIE_DEBT"
const BET_P3_LIE_APPLAUSE: StringName = &"P3_LIE_APPLAUSE"

const CONDANNA_ANCORA: StringName = &"CONDANNA_ANCORA"
const CONDANNA_NON_DOVEVO_PROVARCI: StringName = &"CONDANNA_NON_DOVEVO_PROVARCI"
const CONDANNA_FIRMATO: StringName = &"CONDANNA_FIRMATO"
const CONDANNA_MI_SONO_FERMATO: StringName = &"CONDANNA_MI_SONO_FERMATO"

const LEVEL3_BET_BEHAVIOR: Dictionary[StringName, StringName] = {
	BET_P3_WAX_SEAL: BET_DEBT_CHAIN,
	BET_P3_BLOOD_LEDGER: BET_BLOOD_TAX,
	BET_P3_DEBT_MIRROR: BET_DEBT_CHAIN,
	BET_P3_CROWD_FEAST: BET_CROW_PLEASER,
	BET_P3_LAST_WAGER: BET_LAST_BREATH,
	BET_P3_RED_VERDICT: BET_BLOOD_TAX,
	BET_P3_CHAIN_OATH: BET_DEBT_CHAIN,
	BET_P3_TITHE_OF_BONE: BET_BLOOD_TAX,
	BET_P3_GLORY_TAX: BET_CROW_PLEASER,
	BET_P3_MERCY_BAIT: BET_CROW_PLEASER,
	BET_P3_SILENCE_BRIBE: BET_DEBT_CHAIN,
	BET_P3_FINAL_APPLAUSE: BET_CROW_PLEASER,
	BET_P3_LIE_MERCY: BET_CROW_PLEASER,
	BET_P3_LIE_DEBT: BET_DEBT_CHAIN,
	BET_P3_LIE_APPLAUSE: BET_LAST_BREATH,
}

const LEVEL3_PACT_UNLOCKS: Dictionary[StringName, StringName] = {
	BET_P3_WAX_SEAL: CONDANNA_FIRMATO,
	BET_P3_BLOOD_LEDGER: CONDANNA_FIRMATO,
	BET_P3_CROWD_FEAST: CONDANNA_FIRMATO,
	BET_P3_CHAIN_OATH: CONDANNA_FIRMATO,
	BET_P3_DEBT_MIRROR: CONDANNA_ANCORA,
	BET_P3_RED_VERDICT: CONDANNA_ANCORA,
	BET_P3_TITHE_OF_BONE: CONDANNA_ANCORA,
	BET_P3_MERCY_BAIT: CONDANNA_ANCORA,
	BET_P3_LAST_WAGER: CONDANNA_MI_SONO_FERMATO,
	BET_P3_GLORY_TAX: CONDANNA_MI_SONO_FERMATO,
	BET_P3_SILENCE_BRIBE: CONDANNA_MI_SONO_FERMATO,
	BET_P3_FINAL_APPLAUSE: CONDANNA_MI_SONO_FERMATO,
	BET_P3_LIE_MERCY: CONDANNA_NON_DOVEVO_PROVARCI,
	BET_P3_LIE_DEBT: CONDANNA_NON_DOVEVO_PROVARCI,
	BET_P3_LIE_APPLAUSE: CONDANNA_NON_DOVEVO_PROVARCI,
}

static func map_level3_behavior(bet_id: StringName) -> StringName:
	return LEVEL3_BET_BEHAVIOR.get(bet_id, bet_id)

static func get_level3_pact_unlock(bet_id: StringName) -> StringName:
	return LEVEL3_PACT_UNLOCKS.get(bet_id, &"")
