class_name GameConstants
extends Node

const PLAYER_MOVE_SPEED := 140.0
const PLAYER_LIGHT_ATTACK_DURATION := 0.18
const PLAYER_LIGHT_ATTACK_DAMAGE := 1
const PLAYER_LIGHT_ATTACK_COOLDOWN := 0.12
const PLAYER_HEAVY_ATTACK_DURATION := 0.32
const PLAYER_HEAVY_ATTACK_DAMAGE := 2
const PLAYER_HEAVY_ATTACK_COOLDOWN := 0.25
const PLAYER_HEAVY_ATTACK_WINDUP := 0.10
const PLAYER_DODGE_DURATION := 0.14
const PLAYER_DODGE_SPEED := 280.0
const PLAYER_HITSTUN_DURATION := 0.12
const PLAYER_KNOCKBACK_FORCE := 220.0
const PLAYER_MAX_HEALTH := 10

const ENEMY_CHASE_RANGE := 220.0
const ENEMY_ATTACK_RANGE := 40.0
const ENEMY_ATTACK_WINDUP := 0.12
const ENEMY_ATTACK_ACTIVE := 0.10
const ENEMY_ATTACK_RECOVERY := 0.25
const ENEMY_FLASH_DURATION := 0.08
const ENEMY_MAX_HP := 3
const ENEMY_MOVE_SPEED := 95.0
const ENEMY_ATTACK_DAMAGE := 1

const ARENA_RADIUS := 280.0
const ARENA_BASE_ENEMY_COUNT := 3
const ARENA_ENEMY_INCREMENT := 2

const RUN_STARTING_COINS := 40
const ARENA_CLEAR_REWARD := 5
